package com.bookstore.entity;
// Generated May 1, 2020 9:29:51 AM by Hibernate Tools 5.2.3.Final

import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookId generated by hbm2java
 */
@Embeddable
public class BookId implements java.io.Serializable {

	private int bookId;
	private String title;
	private String author;
	private String description;
	private String isbn;
	private byte[] image;
	private float price;
	private Date publishDate;
	private Date lastUpdateTime;
	private int categoryId;

	public BookId() {
	}

	public BookId(int bookId, String title, String author, String description, String isbn, byte[] image, float price,
			Date publishDate, Date lastUpdateTime, int categoryId) {
		this.bookId = bookId;
		this.title = title;
		this.author = author;
		this.description = description;
		this.isbn = isbn;
		this.image = image;
		this.price = price;
		this.publishDate = publishDate;
		this.lastUpdateTime = lastUpdateTime;
		this.categoryId = categoryId;
	}

	@Column(name = "book_id", unique = true, nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "title", unique = true, nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", nullable = false, length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isbn", nullable = false, length = 15)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookId))
			return false;
		BookId castOther = (BookId) other;

		return (this.getBookId() == castOther.getBookId())
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getAuthor() == castOther.getAuthor()) || (this.getAuthor() != null
						&& castOther.getAuthor() != null && this.getAuthor().equals(castOther.getAuthor())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null && castOther.getIsbn() != null
						&& this.getIsbn().equals(castOther.getIsbn())))
				&& ((this.getImage() == castOther.getImage()) || (this.getImage() != null
						&& castOther.getImage() != null && Arrays.equals(this.getImage(), castOther.getImage())))
				&& (this.getPrice() == castOther.getPrice())
				&& ((this.getPublishDate() == castOther.getPublishDate())
						|| (this.getPublishDate() != null && castOther.getPublishDate() != null
								&& this.getPublishDate().equals(castOther.getPublishDate())))
				&& ((this.getLastUpdateTime() == castOther.getLastUpdateTime())
						|| (this.getLastUpdateTime() != null && castOther.getLastUpdateTime() != null
								&& this.getLastUpdateTime().equals(castOther.getLastUpdateTime())))
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getAuthor() == null ? 0 : this.getAuthor().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		result = 37 * result + (getImage() == null ? 0 : Arrays.hashCode(this.getImage()));
		result = 37 * result + (int) this.getPrice();
		result = 37 * result + (getPublishDate() == null ? 0 : this.getPublishDate().hashCode());
		result = 37 * result + (getLastUpdateTime() == null ? 0 : this.getLastUpdateTime().hashCode());
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
